[workspace]
members = [
  "crates/bin/editor",
  "crates/bin/tests",

  "crates/lib/tdrengine-core",
  "crates/lib/tdrengine-common",
  "crates/lib/tdrengine-asset-pipe",
  "crates/lib/tdrengine-shader-compiler",
]

exclude = ["benches"]